"""
train_model.py — Model Training and Evaluation Pipeline

This module trains and evaluates multiple machine learning classifiers to predict
diabetes complication risk across three categories. Each category is trained on
labels generated by the clinical rule matrix (rule_matrix.py).

Key features:
- Class distribution analysis (addresses class imbalance concerns)
- 5-fold stratified cross-validation with mean ± std reporting (Issue #10)
- Train/test evaluation on 80/20 split
- Feature importance extraction and storage (Issue #7)
- Comparison of 3 algorithms per category
- Saves best-performing model and full summary to model/

Methodology Reference:
- Dataset: CDC Diabetes Health Indicators (BRFSS 2015), 35,346 diabetic-positive respondents
- Feature count: 13 (see FEATURE_COLUMNS)
- Classes: Low, Moderate, High (imbalanced; see class distribution output)
- Thresholds: Rule matrix converts point totals to labels; see rule_matrix.py MAX_SCORES

Usage:
    python train_model.py

Output:
    - model/cardiovascular_model.pkl
    - model/neuropathy_mobility_model.pkl
    - model/general_burden_model.pkl
    - model/training_summary.json (includes CV scores, feature importances, etc.)

For methodology chapter, see METHODOLOGY.md
"""

import os
import json
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import (
    classification_report, confusion_matrix, accuracy_score,
    roc_auc_score, roc_curve, auc, precision_recall_curve, f1_score
)
import joblib

from rule_matrix import compute_all_risks

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

FEATURE_COLUMNS = [
    "HighBP", "HighChol", "Smoker", "HeartDiseaseorAttack", "Stroke",
    "BMI", "Age", "DiffWalk", "PhysHlth", "GenHlth", "MentHlth",
    "NoDocbcCost", "Sex",
]

CATEGORIES = ["cardiovascular", "neuropathy_mobility", "general_burden"]

CANDIDATE_MODELS = {
    "Decision Tree": lambda: DecisionTreeClassifier(max_depth=5, random_state=42),
    "Logistic Regression": lambda: make_pipeline(
        StandardScaler(), LogisticRegression(max_iter=2000, random_state=42)
    ),
    "Random Forest": lambda: RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42),
}


def load_and_label(path=None):
    """
    Load diabetes dataset and apply rule matrix labels.
    
    Args:
        path (str, optional): Path to CSV file. Defaults to data/diabetes_dataset.csv
        
    Returns:
        pd.DataFrame: Original data with 3 new columns (label_cardiovascular, 
                      label_neuropathy_mobility, label_general_burden)
                      
    Raises:
        FileNotFoundError: If data file not found at specified path
    """
    if path is None:
        path = os.path.join(BASE_DIR, "data", "diabetes_dataset.csv")
    df = pd.read_csv(path)
    labels = {cat: [] for cat in CATEGORIES}
    for _, row in df.iterrows():
        risks = compute_all_risks(row.to_dict())
        for cat in CATEGORIES:
            labels[cat].append(risks[cat]["label"])
    for cat in CATEGORIES:
        df[f"label_{cat}"] = labels[cat]
    return df


def train_and_evaluate(df):
    """
    Train and evaluate three ML algorithms for each complication category.
    
    Performs:
    1. Class distribution analysis (detects imbalance)
    2. 5-fold stratified cross-validation on training set (mean ± std accuracy)
    3. Train on 80%, evaluate on 20% held-out test set
    4. Extracts and stores feature importances for explainability
    5. Selects best-performing model per category
    6. Saves models and full summary to model/ directory
    
    Args:
        df (pd.DataFrame): DataFrame with features and label_* columns from load_and_label()
        
    Outputs:
        model/{category}_model.pkl: Trained classifier for each category
        model/training_summary.json: Summary with CV scores, accuracy, feature importances
    """
    X = df[FEATURE_COLUMNS]
    summary = {}

    print("\n" + "="*80)
    print("CLASS DISTRIBUTION ANALYSIS")
    print("="*80)

    for cat in CATEGORIES:
        y = df[f"label_{cat}"]
        label_counts = y.value_counts()
        label_pcts = y.value_counts(normalize=True) * 100
        print(f"\n{cat.upper()}:")
        for label in ["Low", "Moderate", "High"]:
            count = label_counts.get(label, 0)
            pct = label_pcts.get(label, 0)
            print(f"  {label:10s}: {count:6d} ({pct:5.1f}%)")

    for cat in CATEGORIES:
        y = df[f"label_{cat}"]
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )

        print(f"\n{'='*80}\n{cat.upper()}\n{'='*80}")
        
        # ===== K-FOLD CROSS-VALIDATION ANALYSIS =====
        print(f"\nK-FOLD CROSS-VALIDATION (5-fold, stratified):")
        kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        cv_results = {}
        
        for name, build in CANDIDATE_MODELS.items():
            clf = build()
            cv_scores = cross_val_score(clf, X_train, y_train, cv=kfold, scoring='accuracy')
            cv_results[name] = {
                "mean": cv_scores.mean(),
                "std": cv_scores.std(),
                "scores": cv_scores
            }
            print(f"  {name:22s} CV accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

        # ===== TRAIN/TEST EVALUATION =====
        print(f"\nTrain/Test Evaluation (80/20 split):")
        results = {}
        for name, build in CANDIDATE_MODELS.items():
            clf = build()
            clf.fit(X_train, y_train)
            y_pred = clf.predict(X_test)
            y_pred_proba = clf.predict_proba(X_test) if hasattr(clf, 'predict_proba') else None
            acc = accuracy_score(y_test, y_pred)
            f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)
            
            results[name] = {
                "model": clf,
                "accuracy": acc,
                "f1": f1,
                "y_pred": y_pred,
                "y_pred_proba": y_pred_proba,
                "cv_mean": cv_results[name]["mean"],
                "cv_std": cv_results[name]["std"],
            }
            print(f"  {name:22s} accuracy: {acc:.4f}, F1 (weighted): {f1:.4f}")

        best_name = max(results, key=lambda n: results[n]["accuracy"])
        best = results[best_name]
        
        print(f"\n  ╔═══════════════════════════════════════════════════════════════╗")
        print(f"  ║ BEST MODEL: {best_name:45s} ║")
        print(f"  ║ Test Accuracy: {best['accuracy']:.4f} | CV Mean: {best['cv_mean']:.4f} ± {best['cv_std']:.4f} ║")
        print(f"  ╚═══════════════════════════════════════════════════════════════╝\n")
        
        print(classification_report(y_test, best["y_pred"], zero_division=0))
        print("Confusion matrix (rows=actual, cols=predicted):")
        print(confusion_matrix(y_test, best["y_pred"], labels=["Low", "Moderate", "High"]))

        # ===== FEATURE IMPORTANCE =====
        feature_importances = {}
        if hasattr(best["model"], "feature_importances_"):
            # Random Forest
            importances = best["model"].feature_importances_
            feature_importances = {
                feat: round(float(imp), 4)
                for feat, imp in zip(FEATURE_COLUMNS, importances)
            }
            print(f"\nFeature Importances ({best_name}):")
            for feat, imp in sorted(feature_importances.items(), key=lambda x: x[1], reverse=True):
                print(f"  {feat:25s}: {imp:.4f}")
        elif hasattr(best["model"], "named_steps"):
            # Logistic Regression in Pipeline
            if hasattr(best["model"].named_steps["logisticregression"], "coef_"):
                coef = best["model"].named_steps["logisticregression"].coef_[0]
                feature_importances = {
                    feat: round(float(abs(c)), 4)
                    for feat, c in zip(FEATURE_COLUMNS, coef)
                }
                print(f"\nCoefficient Magnitudes ({best_name}):")
                for feat, imp in sorted(feature_importances.items(), key=lambda x: x[1], reverse=True):
                    print(f"  {feat:25s}: {imp:.4f}")
        elif hasattr(best["model"], "tree_"):
            # Decision Tree
            importances = best["model"].tree_.feature_importances_
            feature_importances = {
                feat: round(float(imp), 4)
                for feat, imp in zip(FEATURE_COLUMNS, importances)
            }
            print(f"\nFeature Importances ({best_name}):")
            for feat, imp in sorted(feature_importances.items(), key=lambda x: x[1], reverse=True):
                print(f"  {feat:25s}: {imp:.4f}")

        # Save models and summaries
        joblib.dump(best["model"], os.path.join(BASE_DIR, "model", f"{cat}_model.pkl"))
        
        summary[cat] = {
            "best_model": best_name,
            "accuracy": round(best["accuracy"], 4),
            "f1_weighted": round(best["f1"], 4),
            "cv_accuracy_mean": round(best["cv_mean"], 4),
            "cv_accuracy_std": round(best["cv_std"], 4),
            "all_models_compared": {
                n: {
                    "test_accuracy": round(r["accuracy"], 4),
                    "f1_weighted": round(r["f1"], 4),
                    "cv_mean": round(r["cv_mean"], 4),
                    "cv_std": round(r["cv_std"], 4),
                }
                for n, r in results.items()
            },
            "feature_importances": feature_importances,
        }

    with open(os.path.join(BASE_DIR, "model", "training_summary.json"), "w") as f:
        json.dump(summary, f, indent=2)

    print("\nSaved best models to model/*.pkl")
    print("Saved training summary to model/training_summary.json")

    return summary


if __name__ == "__main__":
    df = load_and_label()
    print(f"Loaded {len(df)} rows.")
    print(df[[f"label_{c}" for c in CATEGORIES]].apply(pd.Series.value_counts))
    train_and_evaluate(df)
